skip_tags: true
clone_depth: 50

os: Visual Studio 2015

environment:
  global:
    BUILD_COMMIT: "4.8.0" # "master" or "4.8.0"
    PYPI_UPLOAD: "false"
    TESTPYPI_UPLOAD: "true" # "true" or "false"
    CONDA_BUILD: "true"
    CONDA_UPLOAD: "false"
    PACKAGE_NAME: arch
    CONDA_NUMPY_VERSION: 1.16
    MPLBACKEND: agg
  TESTPYPI_USERNAME:
    secure: 9D67F9Bcy8PITwg1cezOgw==
  TESTPYPI_PASSWORD:
    secure: sEkgnJNTN/bQu3Lh8PysOA==
  PYPI_USERNAME:
    secure: 9D67F9Bcy8PITwg1cezOgw==
  PYPI_PASSWORD:
    secure: ufGrse+xSx3blI6bh9bnSg==
  ANACONDA_USERNAME:
    secure: 9D67F9Bcy8PITwg1cezOgw==
  ANACONDA_TOKEN:
    secure: sGNIyeEysSzD4W0Q9SMB2sK69a5hiM6qGIGPHhtCH9vpGrlSN7nOXr/zbg4X+vvK
  matrix:
    - PY_VER: 2.7
      PYTHON_ARCH: "x86"
    - PY_VER: 2.7
      PYTHON_ARCH: "x86_64"
    - PY_VER: 3.5
      PYTHON_ARCH: "x86_64"
    - PY_VER: 3.5
      PYTHON_ARCH: "x86"
    - PY_VER: 3.6
      PYTHON_ARCH: "x86_64"
    - PY_VER: 3.6
      PYTHON_ARCH: "x86"
    - PY_VER: 3.7
      PYTHON_ARCH: "x86_64"
    - PY_VER: 3.7
      PYTHON_ARCH: "x86"

platform:
    - x64

build_script:
  - git submodule update --init --recursive
  - ps: Start-FileDownload "https://repo.continuum.io/miniconda/Miniconda3-latest-Windows-$env:PYTHON_ARCH.exe" C:\Miniconda.exe; echo "Finished downloading miniconda"
  - cmd: C:\Miniconda.exe /S /D=C:\Py
  - SET PATH=C:\Py;C:\Py\Scripts;C:\Py\Library\bin;%PATH%
  - echo "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64 > "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\amd64/vcvars64.bat"
  - conda config --set always_yes yes
  - conda update conda --quiet
  - conda create -n arch-build python=%PY_VER% numpy cython nose pytest wheel scipy statsmodels --quiet
  - activate arch-build
  - python -m pip install -U pip
  - pip install cached_property
  - set "WHEELBUILDER_DIR=%cd%"

test_script:
  - echo %cd%
  - cd arch
  - git checkout %BUILD_COMMIT%
  - python setup.py bdist_wheel
  - set "REPO_DIR=%cd%"
  - cd ..

  - pip install --pre --no-index --find-links %REPO_DIR%\dist\ %PACKAGE_NAME%

  - mkdir _for_testing
  - cd _for_testing
  - python -c "import arch; arch.test()"
  
on_success:
  - echo "Upload here"
  - cd %WHEELBUILDER_DIR%\
  - echo %cd%
  - pip install twine
  - twine-upload.bat
  - build-conda.bat
