skip_tags: true
clone_depth: 50

os: Visual Studio 2015

environment:
  global:
    BUILD_COMMIT: v1.14.1
    TESTPYPI_UPLOAD: "true"
    PYPI_UPLOAD: "false"
    PACKAGE_NAME: randomgen
  TESTPYPI_USERNAME:
    secure: 9D67F9Bcy8PITwg1cezOgw==
  TESTPYPI_PASSWORD:
    secure: sEkgnJNTN/bQu3Lh8PysOA==
  PYPI_USERNAME:
    secure: 9D67F9Bcy8PITwg1cezOgw==
  PYPI_PASSWORD:
    secure: ufGrse+xSx3blI6bh9bnSg==
  matrix:
    - PY_VER: 2.7
      PYTHON_ARCH: "x86"
    - PY_VER: 2.7
      PYTHON_ARCH: "x86_64"
    - PY_VER: 3.5
      PYTHON_ARCH: "x86_64"
    - PY_VER: 3.5
      PYTHON_ARCH: "x86"
    - PY_VER: 3.6
      PYTHON_ARCH: "x86_64"
    - PY_VER: 3.6
      PYTHON_ARCH: "x86"

platform:
    - x64

build_script:
  - git submodule update --init --recursive
  - ps: Start-FileDownload "https://repo.continuum.io/miniconda/Miniconda3-latest-Windows-$env:PYTHON_ARCH.exe" C:\Miniconda.exe; echo "Finished downloading miniconda"
  - cmd: C:\Miniconda.exe /S /D=C:\Py
  - SET PATH=C:\Py;C:\Py\Scripts;C:\Py\Library\bin;%PATH%
  - conda config --set always_yes yes
  - conda update conda --quiet
  - conda create -n randomgen-build python=%PY_VER% numpy cython nose pytest wheel --quiet
  - activate randomgen-build
  - python -m pip install -U pip
  - set "WHEELBUILDER_DIR=%cd%"

test_script:
  - echo %cd%
  - cd randomgen
  - git checkout %BUILD_COMMIT%
  - python setup.py bdist_wheel
  - set "REPO_DIR=%cd%"
  - cd ..

  - pip install --pre --no-index --find-links %REPO_DIR%\dist\ %PACKAGE_NAME%

  - mkdir _for_testing
  - cd _for_testing
  - pytest --pyargs randomgen
  
on_success:
  - echo "Upload here"
  - cd %WHEELBUILDER_DIR%\
  - echo %cd%
  - pip install twine
  - twine_upload.bat
  